### ISSUE TITLE
Don't RETURN elements on Web

### ISSUE THREAD

**Issue by hmizael** [AvitalTamir/cyphernetes#143] opened 2024-11-05 16:30 UTC
Hi, my english is terrible, sorry.

In Web, the queries dont return:
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/5e8da303-9324-440e-b80c-c0f8252739b1">

**Comment by AvitalTamir** [comment] 2024-11-05 17:36
Hi @hmizael, there isn't such a propert as NAME, you're most likely looking for `.metadata.name` - though there is no need to ask for it explicit as name is always returned.

You can return `p` if you want to see the entire spec and discover the resource spec.

Closing as this is not an issue.

**Comment by AvitalTamir** [comment] 2024-11-05 17:43
Hi @hmizael - thanks for reporting.
I initially closed it as not an issue because I looked at your query and answered NAME isn't a property and you're probably looking for `.metadata.name` - however I now see in your screenshot that your shell did return results (though NAME is null as expected... `.metadata.name` is returned by default as `name`).

So I'm not sure what the issue is and why web doesn't work. I also see some artifacts I don't recognize in the web screenshot (YAML/JSON buttons placed incorrectly).

Can you please provide more information? Which OS, Browser are you using?

**Comment by hmizael** [comment] 2024-11-05 18:40
No problem, new test:
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/8f690814-252b-4b43-8d3e-cd5e29b17f69">

I'm using Windows 11 Pro 24H2 26100.2161, Windows Terminal 1.21.2911.0, Powershell 7.4.6 and Google Chrome 130.0.6723.92

**Comment by hmizael** [comment] 2024-11-05 18:43
In the Microsoft Edge 130.0.2849.68 browser I had the same result, that is, no results.

**Comment by AvitalTamir** [comment] 2024-11-05 18:44
Thanks, will try to reproduce 👍

**Comment by scraly** [comment] 2024-12-17 08:27
Hi,
I have the same issues. The web interface is not working for me also.

I freshly installed cyphernetes, I tested it in two clusters.
The query and shell works but not the web interface.

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/ba6c1758-ac8f-48e8-926b-92e369896616" />

Tested on Firefox on a mac m1.

**Comment by AvitalTamir** [comment] 2024-12-17 08:31
Hey @scraly, thanks for reporting!
My partners and I were not able to reproduce this up until now, maybe your report can help us get there. I have an m1 Mac on hand where I can install Firefox and test this, hopefully I'm able to reproduce.
Will update here with results.

**Comment by AvitalTamir** [comment] 2024-12-17 09:12
Sadly I'm unable to reproduce this on m1 / firefox.
We'll increase the effort on trying to figure this issue out, as more users on more platforms are experiencing it.

@scraly @hmizael  if there's any more information on your system you think is relevant that you want to include, let us know.

Thanks again, to both of you.

**Comment by AvitalTamir** [comment] 2024-12-25 09:47
If you're reading this and this is happening to you too - we need help!
If you're willing to send us some more debug info, hop on a chat to try and figure this out - or even want to submit a patch - please let me know 🙏

**Comment by viniciusartur** [comment] 2024-12-25 19:53
I was able to reproduce this issue by using a Kubernetes context with a namespace different than the default one.
After investigation, I found that the culprit was that the `default` namespace was hardcoded for the workflow to execute queries for the **web** interface:
https://github.com/AvitalTamir/cyphernetes/blob/a8a3d4a9a1412e8326d8d3a2fe710287af241205/cmd/cyphernetes/api.go#L45
https://github.com/AvitalTamir/cyphernetes/blob/a8a3d4a9a1412e8326d8d3a2fe710287af241205/cmd/cyphernetes/api.go#L54

Notice that the issue doesn't happen via the **shell** interface because the `default` namespace is not hardcoded there:
https://github.com/AvitalTamir/cyphernetes/blob/a8a3d4a9a1412e8326d8d3a2fe710287af241205/cmd/cyphernetes/shell.go#L562

---

However, this issue is not reproducing in latest master anymore since this was fixed on https://github.com/AvitalTamir/cyphernetes/pull/151.

Given that, I think this issue can be closed, @AvitalTamir.

---
How to reproduce this issue in a minimal way:

1. Start a k3s cluster
2. Create a new namespace:
```
kubectl create namespace test
```
3. Create a pod in the non-default namespace:
```
kubectl run test2 --namespace test --image alpine --command -- sleep 9999
```
4. Change the namespace to `test` for the k3s context by editing the file `/etc/rancher/k3s/k3s.yaml` as explained in https://stackoverflow.com/a/46929735
5. Confirm that you're using a non-default namespace:
```
❯ kubectl config get-contexts
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
*         default   default   default    test
```
6. Run `./cyphernetes web`
7. Use the query:
```
MATCH (p:POD) RETURN p.name
```

**Comment by AvitalTamir** [comment] 2024-12-26 03:27
@viniciusartur this is incredible, thank you so much for helping getting to the bottom of this!
I remember coming across this line when I did the refactoring and thinking this doesn't look right - but didn't make the connection.

No need for a patch, we're aiming to complete all v0.15 tasks in a few days and make the release.
And thanks so much for the detailed report 🙏

**Closed by AvitalTamir** 2024-12-26 03:27 UTC
Labels: bug, help wanted, web
